plugins:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.1

Naming/BinaryOperatorParameterName:
  Enabled: false
