inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Naming/FileName:
  Exclude:
    - Gemfile

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
