require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake


inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 30

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
