
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/FileName:
  Exclude:
    - Gemfile

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
