plugins:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.1

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Naming/BinaryOperatorParameterName:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
