inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake


# inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
