require 'minting/money/allocation'
require 'minting/money/arithmetics'
require 'minting/money/coercion'
require 'minting/money/comparable'
require 'minting/money/conversion'
require 'minting/money/formatting'
require 'minting/money/money'
